# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\umk54\OneDrive\Masaüstü\copy\gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"background-color: rgb(19, 19, 19);\n"
"\n"
"}\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 1, 4, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 0, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("#frame_2 {\n"
"background-color: rgb(206, 215, 224);\n"
"border-radius : 10px;\n"
"}")
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalGPS = QtWidgets.QVBoxLayout()
        self.verticalGPS.setObjectName("verticalGPS")
        self.verticalLayoutGPS = QtWidgets.QVBoxLayout()
        self.verticalLayoutGPS.setObjectName("verticalLayoutGPS")
        self.verticalGPS.addLayout(self.verticalLayoutGPS)
        self.labelGPS = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.labelGPS.setFont(font)
        self.labelGPS.setStyleSheet("color: rgb(19, 19, 19);")
        self.labelGPS.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGPS.setObjectName("labelGPS")
        self.verticalGPS.addWidget(self.labelGPS)
        self.verticalGPS.setStretch(0, 80)
        self.verticalGPS.setStretch(1, 20)
        self.verticalLayout_2.addLayout(self.verticalGPS)
        spacerItem5 = QtWidgets.QSpacerItem(17, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.verticalLayout_1 = QtWidgets.QVBoxLayout()
        self.verticalLayout_1.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_1.setObjectName("verticalLayout_1")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_1.addLayout(self.verticalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setStyleSheet("background-color: rgb(5, 69, 105);\n"
"color: rgb(206, 215, 224);\n"
"min-height: 30px;\n"
"min-width: 80px;\n"
"border-radius: 5px;")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setStyleSheet("background-color: rgb(5, 69, 105);\n"
"color: rgb(206, 215, 224);\n"
"min-height: 30px;\n"
"min-width: 80px;\n"
"border-radius: 5px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.horizontalLayout_3.setStretch(0, 5)
        self.horizontalLayout_3.setStretch(1, 40)
        self.horizontalLayout_3.setStretch(2, 10)
        self.horizontalLayout_3.setStretch(3, 40)
        self.horizontalLayout_3.setStretch(4, 5)
        self.verticalLayout_1.addLayout(self.horizontalLayout_3)
        self.verticalLayout_1.setStretch(0, 90)
        self.verticalLayout_1.setStretch(1, 10)
        self.verticalLayout_2.addLayout(self.verticalLayout_1)
        spacerItem9 = QtWidgets.QSpacerItem(17, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem9)
        self.verticalFrame = QtWidgets.QFrame(self.frame_2)
        self.verticalFrame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayoutGyro_5 = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayoutGyro_5.setObjectName("verticalLayoutGyro_5")
        self.verticalLayoutGyro = QtWidgets.QVBoxLayout()
        self.verticalLayoutGyro.setObjectName("verticalLayoutGyro")
        self.verticalLayoutGyro_5.addLayout(self.verticalLayoutGyro)
        self.verticalLayoutLabel = QtWidgets.QVBoxLayout()
        self.verticalLayoutLabel.setObjectName("verticalLayoutLabel")
        self.labelGyro = QtWidgets.QLabel(self.verticalFrame)
        self.labelGyro.setStyleSheet("color: rgb(19, 19, 19);")
        self.labelGyro.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGyro.setObjectName("labelGyro")
        self.verticalLayoutLabel.addWidget(self.labelGyro)
        self.verticalLayoutGyro_5.addLayout(self.verticalLayoutLabel)
        self.verticalLayoutGyro_5.setStretch(0, 85)
        self.verticalLayoutGyro_5.setStretch(1, 15)
        self.verticalLayout_2.addWidget(self.verticalFrame)
        self.verticalLayout_2.setStretch(0, 30)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 38)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.setStretch(4, 30)
        self.gridLayout_2.addWidget(self.frame_2, 1, 3, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridFrame = QtWidgets.QFrame(self.centralwidget)
        self.gridFrame.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(206, 215, 224);\n"
"")
        self.gridFrame.setObjectName("gridFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.gridFrame)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem10, 0, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem11, 2, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem12, 1, 0, 1, 1)
        self.verticalFrame_2 = QtWidgets.QFrame(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalFrame_2.sizePolicy().hasHeightForWidth())
        self.verticalFrame_2.setSizePolicy(sizePolicy)
        self.verticalFrame_2.setStyleSheet("border-image: url(:/TeamImuTogay/logo.jpg);\n"
"color: rgb(19, 19, 19);\n"
"border-radius: 5px;\n"
"")
        self.verticalFrame_2.setObjectName("verticalFrame_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalFrame_2)
        self.verticalLayout_6.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout.addWidget(self.verticalFrame_2, 1, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem13, 1, 2, 1, 1)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(1, 96)
        self.gridLayout.setColumnStretch(2, 2)
        self.gridLayout.setRowStretch(0, 2)
        self.gridLayout.setRowStretch(1, 96)
        self.gridLayout.setRowStretch(2, 2)
        self.horizontalLayout.addWidget(self.gridFrame)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem14)
        self.verticalFrame_3 = QtWidgets.QFrame(self.centralwidget)
        self.verticalFrame_3.setStyleSheet("#verticalFrame_3 {\n"
"background-color: rgb(85, 145, 169);\n"
"border-radius : 10px;\n"
"}")
        self.verticalFrame_3.setObjectName("verticalFrame_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalFrame_3)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setContentsMargins(10, 3, 5, 6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalFrame_31 = QtWidgets.QFrame(self.verticalFrame_3)
        self.verticalFrame_31.setStyleSheet("background-color: rgb(206, 215, 224);\n"
"color: rgb(19, 19, 19);\n"
"border-radius: 5px;")
        self.verticalFrame_31.setObjectName("verticalFrame_31")
        self.verticalLayout_52 = QtWidgets.QVBoxLayout(self.verticalFrame_31)
        self.verticalLayout_52.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_52.setObjectName("verticalLayout_52")
        self.labelGondermeSaati = QtWidgets.QLabel(self.verticalFrame_31)
        self.labelGondermeSaati.setStyleSheet("color: rgb(19, 19, 19);")
        self.labelGondermeSaati.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labelGondermeSaati.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGondermeSaati.setObjectName("labelGondermeSaati")
        self.verticalLayout_52.addWidget(self.labelGondermeSaati)
        self.verticalLayout_9.addWidget(self.verticalFrame_31)
        self.gridLayout_3.addLayout(self.verticalLayout_9, 1, 0, 1, 1)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setContentsMargins(5, 6, 10, 3)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.verticalFrame_34 = QtWidgets.QFrame(self.verticalFrame_3)
        self.verticalFrame_34.setStyleSheet("background-color: rgb(206, 215, 224);\n"
"color: rgb(19, 19, 19);\n"
"border-radius: 5px;")
        self.verticalFrame_34.setObjectName("verticalFrame_34")
        self.verticalLayout_55 = QtWidgets.QVBoxLayout(self.verticalFrame_34)
        self.verticalLayout_55.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_55.setObjectName("verticalLayout_55")
        self.labelPaketNumarasi = QtWidgets.QLabel(self.verticalFrame_34)
        self.labelPaketNumarasi.setStyleSheet("color: rgb(19, 19, 19);")
        self.labelPaketNumarasi.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labelPaketNumarasi.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPaketNumarasi.setObjectName("labelPaketNumarasi")
        self.verticalLayout_55.addWidget(self.labelPaketNumarasi)
        self.verticalLayout_22.addWidget(self.verticalFrame_34)
        self.gridLayout_3.addLayout(self.verticalLayout_22, 0, 2, 1, 1)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setContentsMargins(5, 6, 5, 3)
        self.verticalLayout_23.setSpacing(4)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.verticalFrame_32 = QtWidgets.QFrame(self.verticalFrame_3)
        self.verticalFrame_32.setStyleSheet("background-color: rgb(206, 215, 224);\n"
"color: rgb(19, 19, 19);\n"
"border-radius: 5px;")
        self.verticalFrame_32.setObjectName("verticalFrame_32")
        self.verticalLayout_53 = QtWidgets.QVBoxLayout(self.verticalFrame_32)
        self.verticalLayout_53.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_53.setObjectName("verticalLayout_53")
        self.labelHataKodu = QtWidgets.QLabel(self.verticalFrame_32)
        self.labelHataKodu.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHataKodu.setObjectName("labelHataKodu")
        self.verticalLayout_53.addWidget(self.labelHataKodu)
        self.verticalLayout_23.addWidget(self.verticalFrame_32)
        self.gridLayout_3.addLayout(self.verticalLayout_23, 0, 1, 1, 1)
        self.verticalLayout_57 = QtWidgets.QVBoxLayout()
        self.verticalLayout_57.setContentsMargins(5, 3, 10, 6)
        self.verticalLayout_57.setObjectName("verticalLayout_57")
        self.verticalFrame_35 = QtWidgets.QFrame(self.verticalFrame_3)
        self.verticalFrame_35.setStyleSheet("background-color: rgb(206, 215, 224);\n"
"color: rgb(19, 19, 19);\n"
"border-radius: 5px;\n"
"")
        self.verticalFrame_35.setObjectName("verticalFrame_35")
        self.verticalLayout_56 = QtWidgets.QVBoxLayout(self.verticalFrame_35)
        self.verticalLayout_56.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_56.setObjectName("verticalLayout_56")
        self.labelUyduStatusu = QtWidgets.QLabel(self.verticalFrame_35)
        self.labelUyduStatusu.setAlignment(QtCore.Qt.AlignCenter)
        self.labelUyduStatusu.setObjectName("labelUyduStatusu")
        self.verticalLayout_56.addWidget(self.labelUyduStatusu)
        self.verticalLayout_57.addWidget(self.verticalFrame_35)
        self.gridLayout_3.addLayout(self.verticalLayout_57, 1, 2, 1, 1)
        self.verticalLayout_58 = QtWidgets.QVBoxLayout()
        self.verticalLayout_58.setContentsMargins(10, 6, 5, 3)
        self.verticalLayout_58.setSpacing(4)
        self.verticalLayout_58.setObjectName("verticalLayout_58")
        self.verticalFrame_8 = QtWidgets.QFrame(self.verticalFrame_3)
        self.verticalFrame_8.setStyleSheet("background-color: rgb(206, 215, 224);\n"
"color: rgb(19, 19, 19);\n"
"border-radius: 5px;")
        self.verticalFrame_8.setObjectName("verticalFrame_8")
        self.verticalLayout_51 = QtWidgets.QVBoxLayout(self.verticalFrame_8)
        self.verticalLayout_51.setContentsMargins(10, -1, -1, -1)
        self.verticalLayout_51.setObjectName("verticalLayout_51")
        self.labelTakmID = QtWidgets.QLabel(self.verticalFrame_8)
        self.labelTakmID.setMaximumSize(QtCore.QSize(16777215, 16777213))
        self.labelTakmID.setStyleSheet("color: rgb(19, 19, 19);")
        self.labelTakmID.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTakmID.setObjectName("labelTakmID")
        self.verticalLayout_51.addWidget(self.labelTakmID)
        self.verticalLayout_58.addWidget(self.verticalFrame_8)
        self.gridLayout_3.addLayout(self.verticalLayout_58, 0, 0, 1, 1)
        self.verticalLayout_59 = QtWidgets.QVBoxLayout()
        self.verticalLayout_59.setContentsMargins(5, 3, 5, 6)
        self.verticalLayout_59.setObjectName("verticalLayout_59")
        self.verticalFrame_33 = QtWidgets.QFrame(self.verticalFrame_3)
        self.verticalFrame_33.setStyleSheet("background-color: rgb(206, 215, 224);\n"
"color: rgb(19, 19, 19);\n"
"border-radius: 5px;")
        self.verticalFrame_33.setObjectName("verticalFrame_33")
        self.verticalLayout_54 = QtWidgets.QVBoxLayout(self.verticalFrame_33)
        self.verticalLayout_54.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_54.setObjectName("verticalLayout_54")
        self.labelIrtifaFarki = QtWidgets.QLabel(self.verticalFrame_33)
        self.labelIrtifaFarki.setAlignment(QtCore.Qt.AlignCenter)
        self.labelIrtifaFarki.setObjectName("labelIrtifaFarki")
        self.verticalLayout_54.addWidget(self.labelIrtifaFarki)
        self.verticalLayout_59.addWidget(self.verticalFrame_33)
        self.gridLayout_3.addLayout(self.verticalLayout_59, 1, 1, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_3)
        self.horizontalLayout.addWidget(self.verticalFrame_3)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem15)
        self.verticalFrame_4 = QtWidgets.QFrame(self.centralwidget)
        self.verticalFrame_4.setStyleSheet("#verticalFrame_4 {\n"
"background-color: rgb(85, 145, 169);\n"
"border-radius : 10px;\n"
"}")
        self.verticalFrame_4.setObjectName("verticalFrame_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalFrame_4)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem16)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setContentsMargins(6, 6, 6, 3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalFrame_36 = QtWidgets.QFrame(self.verticalFrame_4)
        self.verticalFrame_36.setStyleSheet("background-color: rgb(206, 215, 224);\n"
"color: rgb(19, 19, 19);\n"
"border-radius: 5px;")
        self.verticalFrame_36.setObjectName("verticalFrame_36")
        self.verticalLayout_60 = QtWidgets.QVBoxLayout(self.verticalFrame_36)
        self.verticalLayout_60.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_60.setObjectName("verticalLayout_60")
        self.labelTasiyicibasinc = QtWidgets.QLabel(self.verticalFrame_36)
        self.labelTasiyicibasinc.setStyleSheet("color: rgb(19, 19, 19);")
        self.labelTasiyicibasinc.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labelTasiyicibasinc.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTasiyicibasinc.setObjectName("labelTasiyicibasinc")
        self.verticalLayout_60.addWidget(self.labelTasiyicibasinc)
        self.verticalLayout_10.addWidget(self.verticalFrame_36)
        self.verticalLayout_8.addLayout(self.verticalLayout_10)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem17)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setContentsMargins(6, 0, 6, 6)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.verticalFrame_37 = QtWidgets.QFrame(self.verticalFrame_4)
        self.verticalFrame_37.setStyleSheet("background-color: rgb(206, 215, 224);\n"
"color: rgb(19, 19, 19);\n"
"border-radius: 5px;")
        self.verticalFrame_37.setObjectName("verticalFrame_37")
        self.verticalLayout_61 = QtWidgets.QVBoxLayout(self.verticalFrame_37)
        self.verticalLayout_61.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_61.setObjectName("verticalLayout_61")
        self.labelTasiyciYukseklik = QtWidgets.QLabel(self.verticalFrame_37)
        self.labelTasiyciYukseklik.setStyleSheet("color: rgb(19, 19, 19);")
        self.labelTasiyciYukseklik.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labelTasiyciYukseklik.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTasiyciYukseklik.setObjectName("labelTasiyciYukseklik")
        self.verticalLayout_61.addWidget(self.labelTasiyciYukseklik)
        self.verticalLayout_24.addWidget(self.verticalFrame_37)
        self.verticalLayout_8.addLayout(self.verticalLayout_24)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem18)
        self.verticalLayout_8.setStretch(0, 6)
        self.verticalLayout_8.setStretch(1, 41)
        self.verticalLayout_8.setStretch(2, 6)
        self.verticalLayout_8.setStretch(3, 41)
        self.verticalLayout_8.setStretch(4, 6)
        self.horizontalLayout.addWidget(self.verticalFrame_4)
        self.horizontalLayout.setStretch(0, 18)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(2, 62)
        self.horizontalLayout.setStretch(3, 2)
        self.horizontalLayout.setStretch(4, 16)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem19)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalframe_2 = QtWidgets.QFrame(self.centralwidget)
        self.horizontalframe_2.setStyleSheet("#horizontalframe_2 { \n"
"border-radius: 10px;\n"
"background-color: rgb(5, 69, 105);\n"
"}")
        self.horizontalframe_2.setObjectName("horizontalframe_2")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.horizontalframe_2)
        self.horizontalLayout_28.setContentsMargins(7, 7, 7, 7)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.comboBoxPort = QtWidgets.QComboBox(self.horizontalframe_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxPort.sizePolicy().hasHeightForWidth())
        self.comboBoxPort.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.comboBoxPort.setFont(font)
        self.comboBoxPort.setStyleSheet("border-radius: 5px;\n"
"min-height: 30px;\n"
"background-color: rgb(206, 215, 224);\n"
"QComboBox::item {\n"
"background-color: rgb(206, 215, 224);\n"
"    color: rgb(19, 19, 19);\n"
"}")
        self.comboBoxPort.setObjectName("comboBoxPort")
        self.horizontalLayout_30.addWidget(self.comboBoxPort)
        self.comboBoxBaudRate = QtWidgets.QComboBox(self.horizontalframe_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxBaudRate.sizePolicy().hasHeightForWidth())
        self.comboBoxBaudRate.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.comboBoxBaudRate.setFont(font)
        self.comboBoxBaudRate.setStyleSheet("border-radius: 5px;\n"
"min-height: 30px;\n"
"background-color: rgb(206, 215, 224);\n"
"QComboBox::item {\n"
"background-color: rgb(206, 215, 224);\n"
"color: rgb(19, 19, 19);\n"
"}")
        self.comboBoxBaudRate.setObjectName("comboBoxBaudRate")
        self.horizontalLayout_30.addWidget(self.comboBoxBaudRate)
        self.verticalLayout_20.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.pushButtonConnect = QtWidgets.QPushButton(self.horizontalframe_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonConnect.sizePolicy().hasHeightForWidth())
        self.pushButtonConnect.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.pushButtonConnect.setFont(font)
        self.pushButtonConnect.setStyleSheet("background-color: rgb(206, 215, 224);\n"
"border-radius: 5px;\n"
"color: rgb(19, 19, 19);\n"
"min-height: 30px;")
        self.pushButtonConnect.setObjectName("pushButtonConnect")
        self.horizontalLayout_31.addWidget(self.pushButtonConnect)
        self.pushButtonDisconnect = QtWidgets.QPushButton(self.horizontalframe_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonDisconnect.sizePolicy().hasHeightForWidth())
        self.pushButtonDisconnect.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.pushButtonDisconnect.setFont(font)
        self.pushButtonDisconnect.setStyleSheet("background-color: rgb(206, 215, 224);\n"
"color: rgb(19, 19, 19);\n"
"border-radius: 5px;\n"
"min-height: 30px;")
        self.pushButtonDisconnect.setObjectName("pushButtonDisconnect")
        self.horizontalLayout_31.addWidget(self.pushButtonDisconnect)
        self.verticalLayout_20.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_29.addLayout(self.verticalLayout_20)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem20)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.horizontalframe_2)
        self.lineEdit_17.setStyleSheet("background-color: rgb(206, 215, 224);\n"
"min-height: 30px;\n"
"border-radius: 5px;")
        self.lineEdit_17.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.horizontalLayout_32.addWidget(self.lineEdit_17)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.horizontalframe_2)
        self.lineEdit_18.setStyleSheet("background-color: rgb(206, 215, 224);\n"
"min-height: 30px;\n"
"border-radius: 5px;")
        self.lineEdit_18.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.horizontalLayout_32.addWidget(self.lineEdit_18)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.horizontalframe_2)
        self.lineEdit_19.setStyleSheet("background-color: rgb(206, 215, 224);\n"
"min-height: 30px;\n"
"border-radius: 8px;")
        self.lineEdit_19.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.horizontalLayout_32.addWidget(self.lineEdit_19)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.horizontalframe_2)
        self.lineEdit_20.setStyleSheet("background-color: rgb(206, 215, 224);\n"
"min-height: 30px;\n"
"border-radius: 5px;")
        self.lineEdit_20.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.horizontalLayout_32.addWidget(self.lineEdit_20)
        self.verticalLayout_21.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.pushButton_9 = QtWidgets.QPushButton(self.horizontalframe_2)
        self.pushButton_9.setStyleSheet("background-color: rgb(206, 215, 224);\n"
"color: rgb(19, 19, 19);\n"
"min-height: 30px;\n"
"min-width: 80px;\n"
"border-radius: 5px;")
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_33.addWidget(self.pushButton_9)
        self.verticalLayout_21.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_29.addLayout(self.verticalLayout_21)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem21)
        self.verticalLayoutFile_6 = QtWidgets.QVBoxLayout()
        self.verticalLayoutFile_6.setObjectName("verticalLayoutFile_6")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.pushButtonFileOpen = QtWidgets.QPushButton(self.horizontalframe_2)
        self.pushButtonFileOpen.setStyleSheet("background-color: rgb(206, 215, 224);\n"
"color: rgb(19, 19, 19);\n"
"min-height: 30px;\n"
"min-width: 80px;\n"
"border-radius: 5px;")
        self.pushButtonFileOpen.setObjectName("pushButtonFileOpen")
        self.horizontalLayout_34.addWidget(self.pushButtonFileOpen)
        self.pushButtonSendVideo = QtWidgets.QPushButton(self.horizontalframe_2)
        self.pushButtonSendVideo.setStyleSheet("background-color: rgb(206, 215, 224);\n"
"color: rgb(19, 19, 19);\n"
"min-height: 30px;\n"
"min-width: 80px;\n"
"border-radius: 5px;")
        self.pushButtonSendVideo.setObjectName("pushButtonSendVideo")
        self.horizontalLayout_34.addWidget(self.pushButtonSendVideo)
        self.horizontalLayout_34.setStretch(0, 50)
        self.horizontalLayout_34.setStretch(1, 50)
        self.verticalLayoutFile_6.addLayout(self.horizontalLayout_34)
        self.progressBar = QtWidgets.QProgressBar(self.horizontalframe_2)
        self.progressBar.setStyleSheet("QProgressBar { \n"
"color: rgb(19, 19, 19);\n"
"border-radius: 5px;\n"
"text-align: center;\n"
"background-color: rgb(206, 215, 224);\n"
"}\n"
"QProgressBar::chunk {\n"
"background-color: rgb(5, 69, 105);\n"
"border-radius: 5px;\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayoutFile_6.addWidget(self.progressBar)
        self.horizontalLayout_29.addLayout(self.verticalLayoutFile_6)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem22)
        self.frame5_5 = QtWidgets.QFrame(self.horizontalframe_2)
        self.frame5_5.setStyleSheet("background-color: rgb(206, 215, 224);\n"
"border-radius:5px;")
        self.frame5_5.setObjectName("frame5_5")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.frame5_5)
        self.verticalLayout_27.setContentsMargins(13, 13, 13, 13)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame5_5)
        self.pushButton_10.setStyleSheet("background-color: rgb(206, 215, 224);\n"
"color: rgb(19, 19, 19);\n"
"min-height: 30px;\n"
"min-width: 80px;\n"
"border-radius: 5px;")
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_27.addWidget(self.pushButton_10)
        self.horizontalLayout_29.addWidget(self.frame5_5)
        self.horizontalLayout_29.setStretch(0, 28)
        self.horizontalLayout_29.setStretch(1, 2)
        self.horizontalLayout_29.setStretch(2, 28)
        self.horizontalLayout_29.setStretch(3, 2)
        self.horizontalLayout_29.setStretch(4, 28)
        self.horizontalLayout_29.setStretch(5, 2)
        self.horizontalLayout_29.setStretch(6, 10)
        self.horizontalLayout_28.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_2.addWidget(self.horizontalframe_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.setStretch(0, 50)
        self.verticalLayout_5.setStretch(1, 1)
        self.verticalLayout_5.setStretch(2, 50)
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem23)
        self.verticalFrame1 = QtWidgets.QFrame(self.centralwidget)
        self.verticalFrame1.setStyleSheet("background-color: rgb(206, 215, 224);\n"
"border-radius: 10px;")
        self.verticalFrame1.setObjectName("verticalFrame1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalFrame1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayoutGraph = QtWidgets.QHBoxLayout()
        self.horizontalLayoutGraph.setObjectName("horizontalLayoutGraph")
        self.verticalLayout_3.addLayout(self.horizontalLayoutGraph)
        spacerItem24 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem24)
        self.horizontalLayoutGraph1 = QtWidgets.QHBoxLayout()
        self.horizontalLayoutGraph1.setObjectName("horizontalLayoutGraph1")
        self.verticalLayout_3.addLayout(self.horizontalLayoutGraph1)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem25)
        self.verticalLayoutTable = QtWidgets.QVBoxLayout()
        self.verticalLayoutTable.setObjectName("verticalLayoutTable")
        self.verticalLayout_3.addLayout(self.verticalLayoutTable)
        self.verticalLayout_3.setStretch(0, 34)
        self.verticalLayout_3.setStretch(1, 1)
        self.verticalLayout_3.setStretch(2, 34)
        self.verticalLayout_3.setStretch(3, 1)
        self.verticalLayout_3.setStretch(4, 30)
        self.verticalLayout_4.addWidget(self.verticalFrame1)
        self.verticalLayout_4.setStretch(0, 18)
        self.verticalLayout_4.setStretch(1, 2)
        self.verticalLayout_4.setStretch(2, 80)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 1, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 64)
        self.gridLayout_2.setColumnStretch(2, 1)
        self.gridLayout_2.setColumnStretch(3, 33)
        self.gridLayout_2.setColumnStretch(4, 1)
        self.gridLayout_2.setRowStretch(0, 1)
        self.gridLayout_2.setRowStretch(1, 98)
        self.gridLayout_2.setRowStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelGPS.setText(_translate("MainWindow", "GPS Latitude:\n"
"GPS Longtitude:\n"
"GPS Altitude: "))
        self.pushButton.setText(_translate("MainWindow", "Kamera Bağlan"))
        self.pushButton_2.setText(_translate("MainWindow", "Kamera Bağlantı Kes"))
        self.labelGyro.setText(_translate("MainWindow", "x:0.0    y:0.0    z:0.0\n"
""))
        self.labelGondermeSaati.setText(_translate("MainWindow", "Gönderim Saati: \n"
""))
        self.labelPaketNumarasi.setText(_translate("MainWindow", "Paket Numarası:\n"
""))
        self.labelHataKodu.setText(_translate("MainWindow", "Hata Kodu:\n"
""))
        self.labelUyduStatusu.setText(_translate("MainWindow", "Uydu Statüsü:\n"
""))
        self.labelTakmID.setText(_translate("MainWindow", "TAKIM ID:\n"
"270432"))
        self.labelIrtifaFarki.setText(_translate("MainWindow", "İrtifa Farkı:\n"
""))
        self.labelTasiyicibasinc.setText(_translate("MainWindow", "Taşıyıcı Basınç: \n"
""))
        self.labelTasiyciYukseklik.setText(_translate("MainWindow", "Taşıyıcı İrtifa: \n"
""))
        self.pushButtonConnect.setText(_translate("MainWindow", "Bağlan"))
        self.pushButtonDisconnect.setText(_translate("MainWindow", "Bağlantı Kes"))
        self.lineEdit_17.setPlaceholderText(_translate("MainWindow", "R"))
        self.lineEdit_18.setPlaceholderText(_translate("MainWindow", "H"))
        self.lineEdit_19.setPlaceholderText(_translate("MainWindow", "R"))
        self.lineEdit_20.setPlaceholderText(_translate("MainWindow", "H"))
        self.pushButton_9.setText(_translate("MainWindow", "Veri Gönder"))
        self.pushButtonFileOpen.setText(_translate("MainWindow", "Dosya Aç"))
        self.pushButtonSendVideo.setText(_translate("MainWindow", "Gönder"))
        self.pushButton_10.setText(_translate("MainWindow", "Taşıyıcıyı\n"
"Ayır"))
import logo_rc
